image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - before: |
      export FLASK_APP=flaskr
      export FLASK_ENV=development

vscode:
  extensions:
    - ms-python.python
    - vscode-icons-team.vscode-icons
    - ritwickdey.liveserver
    - dracula-theme.theme-dracula
    - enkia.tokyo-night
