tasks:
  - init: |
      pip3 install --upgrade pip
      pip3 install -r requirements.txt

ports:
  - port: 5000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - vscode-icons-team.vscode-icons
    - ritwickdey.liveserver
    - dracula-theme.theme-dracula
    - enkia.tokyo-night
    - ms-toolsai.jupyter
