image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - init: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt

vscode:
  extensions:
    - ms-python.python
    - vscode-icons-team.vscode-icons
    - ritwickdey.liveserver
    - dracula-theme.theme-dracula
    - enkia.tokyo-night
